### ISSUE TITLE
Add method for detecting a default Project ID

### ISSUE THREAD

**Issue by bshaffer** [googleapis/google-auth-library-php#135]
The python auth library has support for detecting the current `Project ID` in several different ways ([see here](https://google-auth.readthedocs.io/en/latest/_modules/google/auth/_default.html#default). If we added support for this in the PHP auth library, it could be used in `google-cloud-php`'s [`ClientTrait`](https://github.com/GoogleCloudPlatform/google-cloud-php/blob/master/src/ClientTrait.php).

This has the advantages of DRY, and would allow us to add the method of retrieving the project ID from the gcloud command line tool and from App Engine standard, neither of which are currently supported by `google-cloud-php`.

**Comment by JamesVanWaza** [comment]
@bshaffer what's the solution for the issue.

**Comment by jdpedrie** [comment]
@JamesVanWaza #230 will address this. Look for it in a near-future release of the Auth library.
