### ISSUE TITLE
Code does not work, gives fatal error 

### ISSUE THREAD

**Issue by TheJadeEmperor** [googleapis/google-auth-library-php#210]
![screenhunter_207 oct 01 00 51](https://user-images.githubusercontent.com/9850773/46270176-2bd1fd00-c514-11e8-9929-67d85fffef37.png)

Fatal error: Class 'Google\Auth\ApplicationDefaultCredentials' not found in C:\wamp\www\google-auth-library-php\call.php on line 15

**Comment by jdpedrie** [comment]
Hi @TheJadeEmperor,

Have you made sure to include the composer autoload file?

```php
include "/path/to/vendor/autoload.php";
```

See the [Composer documentation](https://getcomposer.org/doc/01-basic-usage.md#autoloading) for more detailed information.

**Comment by dwsupplee** [comment]
I'm going to close this out now @TheJadeEmperor, please feel free to re-open if @jdpedrie's suggestion doesn't do the trick :).
