### ISSUE TITLE
Do we have to refresh the access token manually ourselves?

### ISSUE THREAD

**Issue by SudoPlz** [googleapis/google-auth-library-php#211]
Hi,

I'm using
```
$this->credentials = ApplicationDefaultCredentials::getCredentials(self::SCOPES);
```

and then

```
$auth_tokens = $this
    ->credentials
    ->getLastReceivedToken();

if (is_null($auth_tokens)) {
    $auth_tokens = $this
                ->credentials
                ->fetchAuthToken();
}

if (array_key_exists('access_token', $auth_tokens))
{
	// print_r((string) $response->getBody());
	return $auth_tokens['access_token'];
}
```

I wonder if we have to refresh the access token manually ourselves, or wether this library takes care of it automatically.
If not, when do we refresh the access token?
Do we just run 

```
$this
     ->credentials
     ->fetchAuthToken();
```

whenever we receive a 401 response?

Thank you in advance

**Comment by dwsupplee** [comment]
Hey @SudoPlz  👋,

You'll want to check the `expires_at` key returned from `getLastReceivedToken` and compare it against the current time.

Something like this:

```php
function getToken($credentials)
{
    $auth_tokens = $credentials
        ->getLastReceivedToken();

    // If we haven't met the expiration time, we can use the token without requesting a new one.
    if (isset($auth_tokens['expires_at']) && $auth_tokens['expires_at'] > time()) {
    	return $auth_tokens['access_token'];
    }

    return $credentials
        ->fetchAuthToken()['access_token'];
}
```

You may find it more useful to utilize a cache, however. It will help manage access tokens for you and only request new ones when they have expired. We even have a [`sysv`](http://php.net/manual/en/ref.sem.php) based cache implementation that will allow you to share tokens between processes, although any [PSR-6 cache implementation](https://www.php-fig.org/psr/psr-6/) will work. Here's an example:

```php
$credentials = ApplicationDefaultCredentials::getCredentials(
	$scopes,
	null,
	null,
	new SysVCacheItemPool
);

$token = $credentials->fetchAccessToken()['access_token'];
```

Hope this helps, if you have any other questions please feel free to re-open.

**Comment by SudoPlz** [comment]
Thank you so much for this answer
