### ISSUE TITLE
Port access token verification from google-api-php-client

### ISSUE THREAD

**Issue by dwsupplee** [googleapis/google-auth-library-php#215]
It seems like it could make sense to port the [`Verify`](https://github.com/googleapis/google-api-php-client/blob/master/src/Google/AccessToken/Verify.php) class from google-api-php-client over to this repository.

/cc @bshaffer, @tmatsuo - do you have any thoughts?

For some further context, please see: https://github.com/googleapis/google-cloud-php/issues/938

**Comment by bshaffer** [comment]
Agreed!

**Comment by bshaffer** [comment]
This is done and is available [here](https://github.com/googleapis/google-auth-library-php#verifying-jwts)!
