### ISSUE TITLE
Add A Filesystem Cache

### ISSUE THREAD

**Issue by bshaffer** [googleapis/google-auth-library-php#218]
We have a simple cache for Memory, but nothing for a filesystem. This is mostly a problem with our [Gsuite Docs](https://developers.google.com/docs/api/quickstart/php), which have bypassed this and use a very crude and poorly implemented file cache.

We could implement a very basic `FilesystemCache` class which takes a `$path` in the constructor and caches files accordingly. This would reduce the lines of code in the above quickstart significantly.

**Comment by dwsupplee** [comment]
I see the value in adding the cache, as we've already started to cross the line with the sysv/in memory implementations - but now it is making we wonder if we should start delegating out to libraries like [symfony/cache](https://github.com/symfony/cache) so we don't continue to creep and want to add more and more implementations we have to maintain.

**Comment by bshaffer** [comment]
Closing because we have decided to not support this
