### ISSUE TITLE
Upcomming shutdown on google+ apis

### ISSUE THREAD

**Issue by MrMeDevelopper** [googleapis/google-auth-library-php#219]
hey, as we know google+ signin will shutdown, does this sdk already uses google sign in, or still uses the google+ scopes that will be shutdown in april? And will this be updated in case its still using deprecated scopes? its very important to get a reply since im implementing this in my website.

thank you

**Comment by dwsupplee** [comment]
Sorry for the delay on a response here @MrMeDevelopper - you should be good to go with what we have in this library.
