### ISSUE TITLE
Does not work on GKE w/ Workload Identity enabled

### ISSUE THREAD

**Issue by mareksuscak** [googleapis/google-auth-library-php#231]
This library doesn't seem to work on GKE w/ [Workload Identity][wi] enabled because according to [the following note][note], GKE metadata server now requires `Metadata-Flavor: Google` HTTP header be present in all requests.

> Compute Engine's [instance metadata][meta] server exposes legacy /0.1/ and /v1beta1/ endpoints, which do not enforce [metadata query headers][querying]. This is a feature in the /v1/ APIs which makes it more difficult for a potential attacker to retrieve instance metadata. Unless specifically required, we recommend you disable these legacy APIs.

However, [GCECredentials](https://github.com/googleapis/google-auth-library-php/blob/master/src/Credentials/GCECredentials.php) isn't providing that in the initial exploratory request.

https://github.com/googleapis/google-auth-library-php/blob/4dd41f92723a76327447763710b0cc8dbe529370/src/Credentials/GCECredentials.php#L191-L194

I got this far in my investigation but I'm not sure if this is all we need to get it working properly. It would also be cool to document it.

PS: Wondering if this bug affects other Google Auth library flavors as well.

GKE inside a Pod ([Workload Identity][wi] enabled)
-------------------------------

<img width="794" alt="gke-workload-identity" src="https://user-images.githubusercontent.com/613647/61627885-27ccc280-ac81-11e9-9bca-c8435d7aa8d3.png">

GCE
---

<img width="1016" alt="gce" src="https://user-images.githubusercontent.com/613647/61627439-10410a00-ac80-11e9-956b-78928bdcda18.png">

Amazon, for comparison
----------------------

<img width="1410" alt="amazon" src="https://user-images.githubusercontent.com/613647/61628687-4df36200-ac83-11e9-81b3-aeee55695fe7.png">

[wi]: https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity
[note]: https://cloud.google.com/kubernetes-engine/docs/how-to/protecting-cluster-metadata#disable-legacy-apis
[meta]: https://cloud.google.com/compute/docs/storing-retrieving-metadata
[querying]: https://cloud.google.com/compute/docs/storing-retrieving-metadata#querying

**Comment by mareksuscak** [comment]
Just tested the patched version and it's working flawlessly!

**Comment by jdpedrie** [comment]
Fantastic! Thanks again for helping us fix it. :)
