### ISSUE TITLE
Fix RSA check in ServiceAccountSignerTrait 

### ISSUE THREAD

**Issue by chrislarosa** [googleapis/google-auth-library-php#236]
The check for `class_exists('RSA')` in ServiceAccountSignerTrait.php fails due to missing namespace _\phpseclib\Crypt\RSA_ https://github.com/googleapis/google-auth-library-php/blob/master/src/ServiceAccountSignerTrait.php#L40

**Comment by jdpedrie** [comment]
Thanks for bringing this to our attention. #237 should fix it.
