### ISSUE TITLE
GCECredentials does not support custom scopes

### ISSUE THREAD

**Issue by samcday** [googleapis/google-auth-library-php#238]
#### Steps to reproduce

```php
    $this->googleClient = new Google_Client();
    $this->googleClient->useApplicationDefaultCredentials();
    $this->googleClient->setScopes(Google_Service_Sheets::SPREADSHEETS);
    $this->sheetsClient = new Google_Service_Sheets($this->googleClient);
    $body = new Google_Service_Sheets_ValueRange();
    $body->setRange("A1");
    $body->setValues([['spaghetti', 'potato']]);
    $this->sheetsClient->spreadsheets_values->update($sheetId, "A1", $body, ['valueInputOption' => 'RAW']);
```

Result:

```json
{
  "error": {
    "code": 403,
    "message": "Request had insufficient authentication scopes.",
    "errors": [
      {
        "message": "Request had insufficient authentication scopes.",
        "domain": "global",
        "reason": "forbidden"
      }
    ],
    "status": "PERMISSION_DENIED"
  }
}
```

The issue is that the `GCECredentials` class is not provided the desired scopes to pass along when asking for a token.

The fact you can even ask for custom scopes from the GCE metadata endpoint is poorly documented. It's not documented in the [main documentation page for GCE metadata](https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#applications), but it *is* [documented in Cloud Run](https://cloud.google.com/run/docs/securing/service-identity#access_tokens). It also mentions that this magic-ish feature is only available for Cloud Functions, Cloud Run services, and App Engine.

**Comment by jdpedrie** [comment]
Thanks for bringing this to our attention. We'll look into it and get back to you as soon as possible!

**Comment by jdpedrie** [comment]
Hi @samcday, I just opened #239 to address this.
