### ISSUE TITLE
verifyIdToken not giving payload for valid id_token

### ISSUE THREAD

**Issue by chiragvels** [googleapis/google-auth-library-php#250]
Hi,

I was using Google Auth library to get data.
I was trying to verify Id Token but not giving payload return

I was using like this 
$payload = $oauth2->verifyIdToken();

It is giving me error **Key may not be emptySome Error Occured!!!**

Can you please see why it is like this?

Thanks,

**Comment by jdpedrie** [comment]
Provide a public key as the first argument to `verifyIdToken()` in order to decode the token.

The documentation for `Google\Auth\OAuth2::verifyIdToken()` states the following:

> if $publicKey is null, the key is decoded without being verified.

However, [`JWT\JWT::decode()`](https://github.com/firebase/php-jwt/blob/5f68890c13b0bb3415861963143831eb6fd42e6e/src/JWT.php#L74-L76) throws an exception if a key is not given.

We'll need to investigate this further.

**Comment by chiragvels** [comment]
Hi @jdpedrie ,

Yes, I have passed $publicKey as first argument but still giving me error.

$publicKey = file_get_contents(__DIR__ . '/fixtures' . '/public.pem');
$payload = $oauth2->verifyIdToken($publicKey);

Thanks,

**Comment by jdpedrie** [comment]
`$publicKey` must not contain what you expect it to. Verify that the file exists and contains the key data. The only place where the error you shared occurs is in checking the value of the public key variable.

**Comment by chiragvels** [comment]
What can be $publicKey? Where I can find?
What do you mean by it contains key data?

Thanks

**Comment by jdpedrie** [comment]
I meant that I do not see any way that you should see the error you shared unless you are not passing in a key.  Make sure `public.pem` contains the key data, and that the path in `file_get_contents()` is correct.

**Comment by chiragvels** [comment]
Ok @jdpedrie , Thanks,

I have taken your pull in my branch. Now I am not getting that error but getting **Wrong audience present in the id token**.

I have checked and found that $this->getAudience() is not returning anything.
Is it due to bug mentioned by you regarding JWT version?

Thanks,

**Comment by jdpedrie** [comment]
You can set the expected audience using `Google\Auth\OAuth2::setAudience()`.

Note that the code in the pull request will not verify that a token signature is valid. It will return the payload without any verification if a public key is not provided. Also, I do not know whether the change will be accepted, so use it with caution. It's never wise to use unreleased code in production. :)

**Comment by danoscarmike** [comment]
@chiragvels are you still having trouble with this? Or can we close this issue? Thanks!

**Comment by chiragvels** [comment]
@danoscarmike ,

It is useful with that Pull Request but it is not recommended way.

You can set the expected audience using Google\Auth\OAuth2::setAudience().

> Note that the code in the pull request will not verify that a token signature is valid. It will return the payload without any verification if a public key is not provided. Also, I do not know whether the change will be accepted, so use it with caution. It's never wise to use unreleased library code in production. :)

So, This issue might be there. I have not tried in recent times.

Thanks,

**Comment by danoscarmike** [comment]
Thanks @chiragvels.

@jdpedrie could you check back in here when you get a chance?

**Comment by jdpedrie** [comment]
Yep, I'll circle back to the PR and implement Brent's feedback. Thank you for the reminder.
