### ISSUE TITLE
How to use the async method with the api client?

### ISSUE THREAD

**Issue by mpjraaij** [googleapis/google-auth-library-php#259]
Hi there,

I see that async is implemented in the http handler: https://github.com/googleapis/google-auth-library-php/blob/6122896969b06745a117aa47a0502fdb7ca024fb/src/HttpHandler/Guzzle6HttpHandler.php#L45

My question is: how do I actually make sure that this async sending is used over the `__invoke` function?

Thanks so much,
Maarten

**Comment by bshaffer** [comment]
Hey there! If you want to invoke this, though, you have a few options:

```php
// Create an authorized HTTP Handler
$http = CredentialsLoader::makeHttpClient(
    ApplicationDefaultCredentials::getCredentials($optionalScope)
);
// Create a callable
$httpAsync = [$http, 'async'];
// invoke the callable
$httpAsync($request);
```

As this is a callable you can also use `call_user_func`:

```php
call_user_func([$http, 'async], $request);
```
