### ISSUE TITLE
missing runtime dependency

### ISSUE THREAD

**Issue by dolvany** [googleapis/google-auth-library-php#271]
```
use Google\Auth\AccessToken;
$token = new AccessToken();
$jwt = $token->verify($iap_jwt, [
  'certsLocation' => AccessToken::IAP_CERT_URL
]);
```

Updated composer to google/auth v1.7.1 and the following error occurs with the above code. Perhaps this dependency should be under require in [composer.json](https://github.com/googleapis/google-auth-library-php/blob/master/composer.json).

`PHP Fatal error:  Uncaught RuntimeException: Please require kelvinmo/simplejwt ^0.2 to use this utility.`

**Comment by jdpedrie** [comment]
We don't require it because it's used for only the one case you've discovered and many users may not have the required extensions compiled into PHP. We may revisit this in the future, but for the time being simply require the dependency in your own project.
