### ISSUE TITLE
FetchAuthTokenCache does not work for id_token

### ISSUE THREAD

**Issue by jsoung** [googleapis/google-auth-library-php#286]
There are two problems:

1. In [FetchAuthTokenCache::fetchAuthToken()](https://github.com/googleapis/google-auth-library-php/blob/master/src/FetchAuthTokenCache.php#L77-L98), the code checks whether the token is an `access_token`, if not, it bails.
2. In [OAuth2::getCacheKey()](https://github.com/googleapis/google-auth-library-php/blob/master/src/OAuth2.php#L540-L548), it returns ` $this->scope` or empty string. This will only work for `access_token`. The function should return `$this->audience` if it's available, which will work for `id_token`.

**Comment by bshaffer** [comment]
This has been added in #291 and released in [`v1.11.0`](https://github.com/googleapis/google-auth-library-php/releases/tag/v1.11.0)
