### ISSUE TITLE
Enable master branch protection

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-auth-library-php#290]
This repository does not seem to have master branch
          protection enabled, at least in the way I'm expecting.
          I was hoping for:

          - master branch protection
          - requiring at least one code reviewer
          - requiring at least two status checks
          - enforcing rules for admins

          Please turn it on!

**Comment by bshaffer** [comment]
@JustinBeckwith I believe the only thing that was missing here was enforcing rules for admins. Can you verify that the proper branch protection is now in place?

**Comment by JustinBeckwith** [comment]
Looks great!
