### ISSUE TITLE
How to use this library with android-publisher api?

### ISSUE THREAD

**Issue by c0dehunter** [googleapis/google-auth-library-php#323]
Hi, I want to be able to access [purchases.products.get](https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.products/get) via this library. I am having a hard time finding a working example, so please excuse if my code doesn't make sense. I tried my best with the documentation that is available,

I generated service account JSON and authorized it in Google Play console.

This is my code:

	<?php
	ini_set('display_errors', 1);
	ini_set('display_startup_errors', 1);
	error_reporting(E_ALL);

	require_once '/home/composer/vendor/autoload.php';

	use Google\Auth\ApplicationDefaultCredentials;
	use GuzzleHttp\Client;
	use GuzzleHttp\HandlerStack;

	putenv('GOOGLE_APPLICATION_CREDENTIALS=/home/googleplayapi/api-48somenumber995.json');

	$scopes = ['https://www.googleapis.com/auth/androidpublisher'];

	// create middleware
	$middleware = ApplicationDefaultCredentials::getMiddleware($scopes);
	$stack = HandlerStack::create();
	$stack->push($middleware);

	// create the HTTP client
	$client = new Client([
	  'handler' => $stack,
	  'base_uri' => 'https://androidpublisher.googleapis.com',
	  'auth' => 'google_auth'  // authorize all requests
	]);

	$packageName = "com.my.appname";
	$productId = "myproductid";
	$token = "gblcsomerandomordertokenIDBuQUohN1pItLJTo";

	// make the request
	$response = $client->get("androidpublisher/v3/applications/{$packageName}/purchases/products/{$productId}/tokens/{$token}");

	// show the result!
	print_r((string) $response->getBody());

	?>

The result I get is:
`'401 Unauthorized' response: { "error": { "code": 401, "message": "The current user has insufficient permissions to perform the requested o (truncated...)`

I triple checked and this service account JSON is authorized for sure:

![image](https://user-images.githubusercontent.com/1484658/107525005-afa55500-6bb6-11eb-8d23-4a28f0701947.png)

![image](https://user-images.githubusercontent.com/1484658/107525111-cc418d00-6bb6-11eb-96ba-0a4a0116b6e5.png)

![image](https://user-images.githubusercontent.com/1484658/107526734-7372f400-6bb8-11eb-9f9e-3969a8585ca0.png)

![image](https://user-images.githubusercontent.com/1484658/107526998-b03eeb00-6bb8-11eb-8003-3db2d6e1366e.png)

I thought maybe I am using this library in a wrong way, so I tried this way, as mentioned in this [issue](https://github.com/googleapis/google-api-php-client/issues/1636#issuecomment-599709048):

	<?php
	ini_set('display_errors', 1);
	ini_set('display_startup_errors', 1);
	error_reporting(E_ALL);

	require_once '/home/composer/vendor/autoload.php';

	use Google\Auth\ApplicationDefaultCredentials;
	use Google\Auth\CredentialsLoader;

	putenv('GOOGLE_APPLICATION_CREDENTIALS=/home/googleplayapi/api-486somenumbere995.json');

	$packageName = "com.my.appname";
	$productId = "myproductid";
	$token = "gblcsomerandomordertokenIDBuQUohN1pItLJTo";

	$credentials = Google\Auth\ApplicationDefaultCredentials::getCredentials();
	$http = Google\Auth\CredentialsLoader::makeHttpClient($credentials);
	$http->request(
	 'GET', "https://androidpublisher.googleapis.com/androidpublisher/v3/applications/{$packageName}/purchases/products/{$productId}/tokens/{$token}"
	);
	?>

But this one also doesn't work:
`'400 Bad Request' response: {"error":"invalid_scope","error_description":"Invalid OAuth scope or ID token audience provided."}
`

**Comment by bshaffer** [comment]
@c0dehunter I am not sure why this is failing, as it may be an authentication issue on the backend. The way you're calling the API is with just the Auth Library. You can try calling it with THIS library (`google/apiclient`), which would look like this:

```php
require 'vendor/autoload.php';

$client = new Google\Client([
    'scopes' => ['https://www.googleapis.com/auth/androidpublisher']
]);
$client->useApplicationDefaultCredentials();

$android = new Google\Service\AndroidPublisher($client);

$packageName = "com.my.appname";
$productId = "myproductid";
$token = "gblcsomerandomordertokenIDBuQUohN1pItLJTo";

// make the request
$response = $android->purchases_products->get($packageName, $productId, $token);

// show the result!
print_r((string) $response->getBody());
```

**Comment by dferenc-netwizzy** [comment]
@bshaffer Your comment helped me to get up and running. Only adding that the response from the get `call` is an instance of [ProductPurchase](https://github.com/googleapis/google-api-php-client-services/blob/3b412587c6e622ceffa70b6f00432dc8800cfb2f/src/AndroidPublisher/ProductPurchase.php#L20), and like that it has no `getBody()` method.

**Comment by bshaffer** [comment]
That makes sense, thank you for the correction!
