### ISSUE TITLE
Method getClientName in interface \Google\Auth\FetchAuthTokenInterface

### ISSUE THREAD

**Issue by ScSherifTarek** [googleapis/google-auth-library-php#329]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-auth-library-php/issues
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+php

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: Windows 10
  - PHP version: 7.4.8
  - Package name and version: google/auth
  
#### Description

`getClientName` method is not defined in the interface [`FetchAuthTokenInterface`](https://github.com/googleapis/google-auth-library-php/blob/master/src/FetchAuthTokenInterface.php) and is used in [`\Google\Auth\FetchAuthTokenCache@FetchAuthTokenCache`](https://github.com/googleapis/google-auth-library-php/blob/master/src/FetchAuthTokenCache.php#L115).

Thanks!

**Comment by dwsupplee** [comment]
`FetchAuthTokenCache` also implements `SignBlobInterface` which implements the method [here](https://github.com/googleapis/google-auth-library-php/blob/master/src/SignBlobInterface.php#L43). Was there an issue you ran into that was problematic?
