### ISSUE TITLE
AccessToken::verify will accept a JWT even if it's missing the audience field

### ISSUE THREAD

**Issue by CarlosCuevas** [googleapis/google-auth-library-php#369]
If I provide a JWT such that the `aud` field is set to a non-matching value with the `audience` option and set `throwException` to true, an exception will be thrown. However, if I simply omit the `aud` field in the JWT it will verify the token, even if I explicitly pass an intended audience. I would expect that if a mismatched audience triggers a thrown exception, an omitted one would too.

Changing the following to also throw when the payload is missing the `aud` field (if `$audience` has also been set) should fix it.

https://github.com/googleapis/google-auth-library-php/blob/9472fa8d2ba4fc4824aa90e2bb2c909aa986d121/src/AccessToken.php#L269-L273

Could be as simple as adding
```php
elseif ($audience) {
    throw new UnexpectedValueException('Audience missing');
}
```

**Comment by bshaffer** [comment]
I agree it seems like if "aud" doesn't exist, it should be treated as an audience mismatch. However, we should verify this is the way it's handled in the spec or other auth libraries before implementing this change here.

**Comment by CarlosCuevas** [comment]
this was fixed, thanks @bshaffer
