### ISSUE TITLE
Can you support PSR Cache in version 3?

### ISSUE THREAD

**Issue by wlasnapl** [googleapis/google-auth-library-php#373]
**Is your feature request related to a problem? Please describe.**
Some other vendor used in my project uses PSR cache in version 3 not in version 2 so there is conflict. 

 **Describe the solution you'd like**
Please support PSR Cache in version 3 also.

 **Describe alternatives you've considered**
I've wrote also to that other vendor to support also version 2. But version 3 is newest so should be also supported by Google Auth

**Comment by wadewomersley** [comment]
Blocking upgrade to PHP8.1 due to this being the only library left that needs 1.0/2.0 and not 3.0.

**Comment by asurcodes** [comment]
In our case, this support is blocking us from adopting Firebase as a push notification service, we are up-to-date using PHP 8.1, so our main option is to use the legacy `SERVER_KEY` authentication mechanism, which is ironic...

IMO droping support for end-of-life PHP version in a new major release (#322) is the best move here, but is a bit worrying the lack of recent progress on the PR, I'm open to help if neccessary.

**Comment by janhenckens** [comment]
Running into similar (blocking) issues here, hope this can be resolved soon.

**Comment by wadewomersley** [comment]
PHP 5.x has been EOL for a few years now (3yr2mo) so I think dropping support for it would certainly raise the least eyebrows.

**Comment by bshaffer** [comment]
I've updated [the PR](https://github.com/googleapis/google-auth-library-php/pull/364) so the library has a minimum of PHP 7.1, and uses the `TypedItem` compatibility layer with `psr 3.0`. 

Please use composer to try this branch out and see if it works for you

```
composer require google/auth:dev-add-typed-cache-item
```

**Comment by bshaffer** [comment]
This is now released in [v1.20.0](https://github.com/googleapis/google-auth-library-php/releases/tag/v1.20.0)
