### ISSUE TITLE
Incompatible types with package psr/cache v3.0.0

### ISSUE THREAD

**Issue by javiermarinros** [googleapis/google-auth-library-php#397]
This error is thrown when trying to use the library in PHP 8.1:

> Declaration of Google\Auth\Cache\Item::getKey() must be compatible with Psr\Cache\CacheItemInterface::getKey()

#### Environment details

  - PHP version: 8.1
  - Package name and version: psr/cache v3.0.0, google/auth v1.21.0

#### Steps to reproduce

Create a new folder and place this files:

#### composer.json
```json
{
  "name": "test/test",
  "require": {
    "php": "^8.0",
    "google/auth": "^v1"
  }
}
```

#### test.php
```php
<?php
require __DIR__ . '/vendor/autoload.php';
$item = new \Google\Auth\Cache\Item('key');
```

And then execute:
> composer install
> php test.php

**Comment by bshaffer** [comment]
Hello @javiermarinros 

In order to preserve Backwards Compatibility, we had to create a _new_ class to implement `CacheItemInterface` for `psr/cache v3.0.0`. That class is called `Google\Auth\Cache\TypedItem`. So if you're using `psr/cache v3.0.0`, your code should look like this instead:

**test.php**
```php
<?php
require __DIR__ . '/vendor/autoload.php';
$item = new \Google\Auth\Cache\TypedItem('key');
```

**Comment by ItsReddi** [comment]
@bshaffer we are getting this error also after updating dependencies.
```
74.78 PHP Fatal error:  Declaration of Google\Auth\Cache\Item::getKey() must be compatible with Psr\Cache\CacheItemInterface::getKey(): string in /var/www/html/vendor/google/auth/src/Cache/Item.php on line 62
#18 74.78 Error: Declaration of Google\Auth\Cache\Item::getKey() must be compatible with Psr\Cache\CacheItemInterface::getKey(): string
```

I am not using the Item directly. I am using: `Google\Service\AndroidPublisher`.
I forced, `psr/cache:^2.0` now but that feels not good.

PHPStan fails also.

**Comment by bshaffer** [comment]
@ItsReddi i don't think you are actually using PSR/cache 2.0. If you were, you wouldn't be getting this error. You're probably loading the psr/cache 3.0 interfaces at some point beforehand on accident.
