### ISSUE TITLE
User Refresh Credentials Authentication flow with Access Token Only

### ISSUE THREAD

**Issue by DeveloperRob** [googleapis/google-auth-library-php#427]
### Current Issue
On Google-Ads-PHP, a feature request was raised where someone using a microservice architecture would like a way to manage retrieval of access tokens themselves (shared between simultaneously running instances) instead of providing a refresh token and having this library obtain the access token. That library wraps around the classes exposed from this library, and while it has `UserRefreshCredentials` which allows authorisation with client id/secret & refresh token, it doesn't allow supplying an access token (although from a theory basis, supplying a valid access token should be sufficient to perform a request)

### Suggested Solution
I am happy to submit a PR here (and then a further PR in Google-Ads-PHP making use of the new code) to solve the problem if the maintainers feel it has merit. In terms of how the solution should be authored I am happy to accept guidance, but my suggestion would be a new class which:
* Extends `UserRefreshCredentials`
* Is constructed with `access_token` and `expires_at`, optionally with `client_id`, `client_secret`, `refresh_token`
  * If passed, code is implemented to allow token refresh
* Has a `getAccessToken` method to get a refreshed token (if one is possible to obtain)

### Open Questions
* Is there a better way to implement support for the reporters use case?
* Should there be any special handling for when an access token has expired _but_ the `expires_at` hasn't passed (e.g. the wrong `expires_at` was passed in)?
* When `expires_at` has passed *and* no `refresh_token` exists, what should `fetchAuthToken` do?
  * Throw an exception (if so what)?

Thanks,
Robert

**Comment by bshaffer** [comment]
Hello!!
If i understand your request correctly, you want to send in the raw access token. I don't know what this use case would be, but you could implement by using [ScopedAccessTokenMiddleware](https://github.com/googleapis/google-auth-library-php/blob/0865c44ab50378f7b145827dfcbd1e7a238f7759/src/Middleware/ScopedAccessTokenMiddleware.php#L95)
