### ISSUE TITLE
Improve local user experience for User Credentials

### ISSUE THREAD

**Issue by TimurSadykov** [googleapis/google-auth-library-php#436]
This is part of the bigger work [go/simplified-local-adc](http://goto.google.com/simplified-local-adc)

User Credentials are now recommended for local development per [go/mitigating-cloud-auth-risk](https://goto.google.com/mitigating-cloud-auth-risk)

However, some errors and warnings still refer to service accounts (see section 1.2 of the [go/simplified-local-adc](http://goto.google.com/simplified-local-adc)):

1. When user does not have credential setup, we do not recommend setting up service account, rather we redirect to a new ADC setup page.
2. (if implemented) We show warning about user credentials only if production environment is detected

Reference Java fix: https://github.com/googleapis/google-auth-library-java/pull/1172

**Comment by bshaffer** [comment]
1. Done in https://github.com/googleapis/google-auth-library-php/pull/440 (mostly just updates the link)
2. There is https://github.com/googleapis/google-cloud-php/blob/main/Core/src/ClientTrait.php#L201-L207 (for handwritten clients only), where we recommend setting up a service account if the project ID is missing. Is this the same thing or related?  If so, by "production environment" do you mean the GCE metadata server, or something else?

**Comment by bshaffer** [comment]
@TimurSadykov could you confirm that there's something else we should do here, or close this issue if not? I blieve this is fixed.

**Comment by TimurSadykov** [comment]
It would be interesting to learn what is the scenario for the 2 in more detail, but for the subject issue - it is fixed
