### ISSUE TITLE
when using SysVCacheItemPool in FPM container subsequent calls fail Request had insufficient authentication scopes.

### ISSUE THREAD

**Issue by pentium10** [googleapis/google-auth-library-php#442]
When using SysVCacheItemPool in a PHP FPM driven container subsequent calls fail: **Request had insufficient authentication scopes.**

#### Environment details

  - OS: PHP FPM instalation  for example `FROM shinsenter/phpfpm-apache:php8.2`
  - PHP version: 8.1-8.2
  - Package name and version: 

#### Steps to reproduce

  1. setup a simple script for PHP with `SysVCacheItemPool` in use

```php
$cache = new SysVCacheItemPool();
$options['authCache'] = $cache;
$bigQuery = new BigQueryClient($options);
```

  2. run this example, it will cache scopes 
  3. create a second example file using $datastore = new DatastoreClient($options);
  4. when you access that feature you get an exception 
  5. Request had insufficient authentication scopes.
  
it turns out, the initial scope it was cached, it's not reset, and on a second attempt when accessing DatastoreClient it fails. 
removing the cache component, the code works Ok

#### Code example

```php
$cache = new SysVCacheItemPool();
```

**Comment by vishwarajanand** [comment]
Closing due to no response.
