### ISSUE TITLE
Undefined array key "id_token" in AuthTokenMiddleware.php

### ISSUE THREAD

**Issue by rajeshreeputra** [googleapis/google-auth-library-php#502]
PHP Warning:  Undefined array key "id_token" in /google-auth-library-php/google-auth-library-php/src/Middleware/AuthTokenMiddleware.php on line 135
More details: https://github.com/googleapis/google-auth-library-php/actions/runs/7035954803/job/19147519180?pr=499#step:5:17

**Comment by bshaffer** [comment]
This has been fixed in #506
