### ISSUE TITLE
Issue in latest version of google/cloud-core (v1.52.10)

### ISSUE THREAD

**Issue by medinekorkut** [googleapis/google-auth-library-php#504]
In RequestWrapper.php line 351:

  [Error]
  Call to undefined method Google\Auth\FetchAuthTokenCache::getFetcher()

**Comment by bshaffer** [comment]
Looks like this was added in version [`1.25.0`](https://github.com/googleapis/google-auth-library-php/releases/tag/v1.25.0) of this library, so you'll want to make sure that your `google/auth` version is updated to that version or higher.

**Comment by bshaffer** [comment]
@medinekorkut  Sorry that we missed this - we should have updated the minimum `google/auth` dependency to be `1.25.0`, but we didn't. This will be fixed in https://github.com/googleapis/google-auth-library-php/issues/504 (but this will not be released until Jan 2nd, as we are currently in a code freeze)

**Comment by medinekorkut** [comment]
roblem 1
    - google/auth[v1.25.0, ..., v1.26.0] require firebase/php-jwt ^5.5||^6.0 -> found firebase/php-jwt[v5.5.0, v5.5.1, v6.0.0, ..., v6.10.0] but it conflicts with your root composer.json require (^3.0).
    - google/auth[v1.27.0, ..., v1.33.0] require firebase/php-jwt ^6.0 -> found firebase/php-jwt[v6.0.0, ..., v6.10.0] but it conflicts with your root composer.json require (^3.0).
    - Root composer.json requires google/auth ^1.25 -> satisfiable by google/auth[v1.25.0, ..., v1.33.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by bshaffer** [comment]
@medinekorkut supply the `-W` option as suggested in the error message
