### ISSUE TITLE
Firebase\JWT\BeforeValidException

### ISSUE THREAD

**Issue by ovayolumit** [googleapis/google-auth-library-php#530]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**

 **Describe the solution you'd like**

 **Describe alternatives you've considered**

 **Additional context**

**Comment by bshaffer** [comment]
You have not provided any additional information regarding your issue. 

WRT the Firebase "BeforeValidException", it means that the `nbf` claim in the JWT you've created is set to a later time than the one you're using. You may need to set `JWT::$leeway = 1` or something along these lines. Please see the https://github.com/firebase/php-jwt repo for more information.
