### ISSUE TITLE
Backporting PHP 8.4 compatibility

### ISSUE THREAD

**Issue by mikkamp** [googleapis/google-auth-library-php#590]
PHP 8.4 compatibility was released in version [1.43.0](https://github.com/googleapis/google-auth-library-php/releases/tag/v1.43.0) through PR #584

We need to offer compatibility to PHP 7.4+ meaning we are currently locked to the last version which supported PHP 7.4 (version [1.37.1](https://github.com/googleapis/google-auth-library-php/releases/tag/v1.37.1))

So we'd like to request for the PHP 8.4 compatibility to be backported to this same version to be able to support PHP 7.4 up to and including PHP 8.4.

**Comment by bshaffer** [comment]
Fixed in release `v1.37.2`
