### ISSUE TITLE
fetchAuthToken vs fetchAccessToken

### ISSUE THREAD

**Issue by bshaffer** [googleapis/google-auth-library-php#71]
Why are the methods named `fetchAuthToken`? It seems like more standard naming would be `fetchAccessToken`. Is there a difference?

**Comment by tbetbetbe** [comment]
fetchAuthToken is more generic; it allows for auth implementations that use tokens that are not strictly 'access_tokens'.

To be strictly in-line with other auth implementations, this method should probably be renamed to getRequestMetadata

**Comment by bshaffer** [comment]
Sounds good, although we should document the differences in the returned metadata.

For instance, `AppIdentityCredentials` returns an array like the following:

```php
[
    'access_token' => 'xyz',
    'expiration_time' => 1444339757
]
```
